"""add life_stage to users

Revision ID: 6e3984e92181
Revises: cfea75561e15
Create Date: 2026-07-09 13:46:47.403129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3984e92181'
down_revision: Union[str, None] = 'cfea75561e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('life_stage', sa.String(length=20), server_default='unsure', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'life_stage')
    # ### end Alembic commands ###
